### ISSUE TITLE
ClearNLP relations

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-incubator/Services#13]

**Comment by marcverhagen** [comment]
Use SemanticRole as the annotation category.

**Comment by marcverhagen** [comment]
ClearNLP is written in Java 8 and apparently needs to be compiled in Java 7 while being wrapped, which doesn't work for our current Tomcats.

**Comment by keighrim** [comment]
[`clearNLP`](https://github.com/clir/clearnlp) is retired, and replaced with [`nlp4j`](https://emorynlp.github.io/nlp4j/). The lappsgrid wrapper for the new `nlp4j` is under development. See https://github.com/lappsgrid-incubator/org.lappsgrid.nlp4j

Closing this issue.
