### ISSUE TITLE
ReVerb

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/Services#5]
See http://reverb.cs.washington.edu/

**Comment by marcverhagen** [comment]
Some notes I made on the Reverb output. Here is the output for "She swam to Paris" (using the jar on the command line):

``` /Users/marc/Downloads/reverb-test-in.txt
1
She 
swam to
Paris   
0
1
1
3
3
4
0.8651335437320878
She swam to Paris .
PRP VBD TO NNP .
B-NP B-VP B-PP B-NP O
she
swim to
paris
```

The real output is 18 tab-separated columns, here put in a one-column per line format. The 18 columns are described in https://github.com/knowitall/reverb. Columns 6-11 are token offsets given the tokenized sentence (column 13). The relation is not given a label, unless we consider "swam to" the label (or its normalized sister "swim to"). ReVerb also gives us parts of speech and chunks, but the example above is not quite enough to see how the chunks work. And it does not look like the relation and argument offsets point to single ReVerb annotations (this may be a feature of the command line output, somebody with Java skills should look at the API).

**Comment by marcverhagen** [comment]
Vocabulary to be updated soon with GenericRelation type. LIF specifications for this are in draft.

**Comment by marcverhagen** [comment]
The vocab was updated and LIF structures were proposed. Wrapping is in progress.

**Comment by keighrim** [comment]
Initial implementation is done, tested, and deployed on Brandeis Tomcat. 

source: https://github.com/brandeis-nlp/edu.brandeis.cs.reverb-web-service
test-ping: http://eldrad.cs-i.brandeis.edu:8282/reverb-web-service/1.0.0-SNAPSHOT/jsServices

**Comment by keighrim** [comment]
The service is published. Closing issue.
